name: Monitor
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  monitor-balance:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: pip install requests
    - run: python monitor.py
